apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
    type: service
spec:
  type: ClusterIP
  selector:
    app: grafana
    type: deploy
  ports:
    - port: 80
      targetPort: grafana-port
      protocol: TCP
      name: grafana-service-port