apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
        type: deploy
    spec:
      containers:
        - name: grafana
          imagePullPolicy: Never
          image: grafana/grafana
          ports:
            - containerPort: 3000
              protocol: TCP
              name: grafana-port