apiVersion: v1
kind: Service
metadata:
  name: service-mongo
  labels:
    kind: service
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 80
      targetPort: mongo-port
      protocol: TCP
      name: mongo-service-port