apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
    type: database
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo_db
          image: mongo
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
              protocol: TCP
              name: mongo-port